services:
  anaconda:
    build:
      context: .
      dockerfile: .docker/Dockerfile

    volumes:
      - ./:/python
    ports:
      - "81:8888"
    command:
        /opt/conda/bin/jupyter notebook --notebook-dir=/python/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    environment:
      - PG_DB_NAME=${PG_DB_NAME}
      - PG_DB_NAME_TEST=${PG_DB_NAME_TEST}
      - PG_DB_PORT=${PG_DB_PORT}
      - PG_DB_USER=${PG_DB_USER}
      - PG_DB_PASS=${PG_DB_PASS}
      - PG_DB_HOST=${PG_DB_HOST}
    tty: true
